### PR TITLE
add helper scripts for *nix based systems and use full angular typescript definitions

### PR DESCRIPTION
**Pull request by jimthedev**
Hi @bkinsey808. Like the project. I created these scripts for my own use but I figured they might be handy for others using this project so I decided to put in a PR. This updates the docs as well.

### CODE REVIEW

**Comment by jimthedev** [comment]
I added another commit. This one fixes some ide's which get mad because you had run `tsd install angular2 --save` when we really want `tsd install angular2/ --save`. The second example installs all of the definitions, including http and the router. Without this, IDEs get mad at missing defs.

**Comment by bkinsey808** [comment]
@jimthedev Thanks so much! You have some great ideas. I appreciate your contribution, and hope to merge when I get a chance to look at this in more detail. Aloha.

**Comment by jimthedev** [comment]
My pleasure, thanks for the great project!

**Comment by jimthedev** [comment]
@bkinsey808 Added two more things to this PR. upgrade to alpha.38 and a clean script that blows away dist/ typings/ node_modules/ which is called at the beginning of setup.sh so that you always get fresh dependencies when running setup.

**Comment by bkinsey808** [comment]
Okay, I merged your pull request. Thank you very much. Happy hacking!

**Comment by jimthedev** [comment]
Thanks!!!

**Comment by bkinsey808** [comment]
@jimthedev  I have a question for you. Do you think it's possible to integrate <a href="http://www.ag-grid.com/">ag-grid</a> with this project? I've tried a couple of times and failed. I'm not sure if it fully integrates with jspm at this point. What do you think?

**Comment by jimthedev** [comment]
@bkinsey808 I haven't tried it out either. I'd imagine it is possible since they have ng2 support. Will have to give it a try some time. I'm also curious about a similar kind of thing that has ionic2 when it comes out. So you'd have api, mobile app, desktop app, shared repo but separate codebases.

**Pull request merged**
